spring:
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      cache-null-values: false
      use-key-prefix: false
  data:
    mongodb:
      database: kafka
  main:
    allow-bean-definition-overriding: true
server:
  port: 8092