version: '3'
services:
  rc-mongo:
    image: mongo
    restart: always
    ports:
      - "5689:5689"
    environment:
      MONGO_INITDB_DATABASE: kafka

  rc-redis:
    container_name: rc-redis
    image: redis:5
    ports:
      - "6379:6379"
    restart: always
